apiVersion: 1
groups:
  - orgId: 1
    name: "API Alerts"
    folder: "Backend Alerts"
    interval: 1m
    rules:
      - uid: api_high_error_rate
        title: "High HTTP 5xx Error Rate"
        condition: A
        data:
          - refId: A
            datasourceUid: prometheus
            relativeTimeRange:
              from: 300
              to: 0
            model:
              expr: sum(rate(school_api_custom_error_count_total{custom_status_code=~"50..."}[1m])) > 10
              refId: A
        for: 2m
        annotations:
          summary: "High API Error Rate detected (more than 10 custom 50xxx errors per sec)"
          description: "The API is experiencing a high volume of custom 50xxx server errors."
        labels:
          severity: critical
