// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using School_Management.API.Data;

#nullable disable

namespace School_Management.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260415021904_CreateSchoolYearInfo")]
    partial class CreateSchoolYearInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef18be90-de43-45db-9c63-8778ff21e786"),
                            ConcurrencyStamp = "ef18be90-de43-45db-9c63-8778ff21e786",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("ddfd9f1c-e824-4dd3-9859-5e12d419145f"),
                            ConcurrencyStamp = "ddfd9f1c-e824-4dd3-9859-5e12d419145f",
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = new Guid("88ad671c-a2bc-4d35-85c6-02f42bfb3a0c"),
                            ConcurrencyStamp = "88ad671c-a2bc-4d35-85c6-02f42bfb3a0c",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassYearId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileTitle")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("FinishTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeacherSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id");

                    b.HasIndex("ClassYearId");

                    b.HasIndex("TeacherSubjectId");

                    b.ToTable("Assignment", t =>
                        {
                            t.HasCheckConstraint("CK_Time_Assignment", "\"StartTime\" < \"FinishTime\"");
                        });
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentClassYearId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentClassYearId", "Date")
                        .IsUnique();

                    b.ToTable("Attendance", t =>
                        {
                            t.HasCheckConstraint("CK_Status_Attendance", "\"Status\" IN ('Vắng mặt', 'Đi trễ', 'Có mặt')");
                        });
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.ClassYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<Guid?>("HomeRoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HomeRoomId");

                    b.HasIndex("SchoolYear", "ClassName")
                        .IsUnique()
                        .HasDatabaseName("UX_ClassYear_Name_Year");

                    b.HasIndex("SchoolYear", "HomeRoomId")
                        .IsUnique();

                    b.ToTable("ClassYear", t =>
                        {
                            t.HasCheckConstraint("CK_ClassYear_Grade", "\"Grade\" >= 10 AND \"Grade\" <= 12");
                        });
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("TeacherSubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherSubjectId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.CourseAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileTitle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId", "Title")
                        .IsUnique();

                    b.ToTable("CourseAssignment", t =>
                        {
                            t.HasCheckConstraint("CK_OrderIndex_CourseAssignment", "\"OrderIndex\" > 0");
                        });
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("FinishTime")
                        .HasColumnType("interval");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int>("Term")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYear", "Term", "StartTime", "Title")
                        .IsUnique();

                    b.ToTable("Events", null, t =>
                        {
                            t.HasCheckConstraint("CK_SchoolYear", " \"SchoolYear\" >= 2000 AND \"SchoolYear\" <= 2100");

                            t.HasCheckConstraint("CK_StartTime_FinishTime", " \"StartTime\" < \"FinishTime\"");

                            t.HasCheckConstraint("CK_Term", " \"Term\" >= 1 AND \"Term\" <= 2");
                        });
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.ExamSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("integer");

                    b.Property<int>("Term")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Title", "Type", "Term", "Grade", "SchoolYear")
                        .IsUnique();

                    b.ToTable("ExamSchedule", null, t =>
                        {
                            t.HasCheckConstraint("CK_Grade_ExamSchedule", "\"Grade\" >= 10 AND \"Grade\" <= 12");

                            t.HasCheckConstraint("CK_SchoolYear_ExamSchedule", "\"SchoolYear\" > 2000 AND \"SchoolYear\" < 2100");

                            t.HasCheckConstraint("CK_Term_ExamSchedule", "\"Term\" >= 1 AND \"Term\" <= 2");
                        });
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.ExamScheduleDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("ExamScheduleId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("FinishTime")
                        .HasColumnType("interval");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExamScheduleId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ExamScheduleDetail", t =>
                        {
                            t.HasCheckConstraint("CK_Time_ExamScheduleDetail", "\"FinishTime\" > \"StartTime\"");
                        });
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.ExamStudentAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamScheduleDetailId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("ExamScheduleDetailId", "StudentId")
                        .IsUnique();

                    b.ToTable("ExamStudentAssignment");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Fee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ClassYearId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClassYearId", "SchoolYear", "Title")
                        .IsUnique();

                    b.ToTable("Fee", null, t =>
                        {
                            t.HasCheckConstraint("CK_Amount_Fee", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_SchoolYear_Fee", "\"SchoolYear\" > 2000");
                        });
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.FeeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("FeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FeeId");

                    b.HasIndex("StudentId");

                    b.ToTable("FeeDetail", null, t =>
                        {
                            t.HasCheckConstraint("CK_AmountDue_Positive", "\"AmountDue\" >= 0");

                            t.HasCheckConstraint("CK_AmountPaid_NotNegative", "\"AmountPaid\" >= 0");

                            t.HasCheckConstraint("CK_Amount_FeeDetail", "\"AmountPaid\" <= \"AmountDue\"");
                        });
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lesson", t =>
                        {
                            t.HasCheckConstraint("CK_OrderIndex_Lesson", "\"OrderIndex\" > 0");
                        });
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.LessonVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPreview")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonVideo", null, t =>
                        {
                            t.HasCheckConstraint("CK_Duration_LessonVideo", "\"Duration\" > 0");

                            t.HasCheckConstraint("CK_OrderIndex_LessonVideo", "\"OrderIndex\" > 0");
                        });
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", t =>
                        {
                            t.HasCheckConstraint("CK_RefreshToken_Expiration", "\"ExpiresAt\" > \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Term")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("StudentId", "SubjectId", "Type", "Term", "SchoolYear")
                        .IsUnique();

                    b.ToTable("Result", null, t =>
                        {
                            t.HasCheckConstraint("CK_SchoolYear_Result", "\"SchoolYear\" > 2000 AND \"SchoolYear\" < 2100");

                            t.HasCheckConstraint("CK_Term_Result", "\"Term\" >= 1 AND \"Term\" <= 2");

                            t.HasCheckConstraint("CK_Value_Result", "\"Value\" >= 0 AND \"Value\" <= 10");

                            t.HasCheckConstraint("CK_Weight_Result", "\"Weight\" >= 1 AND \"Weight\" <= 3");
                        });
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassYearId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("integer");

                    b.Property<int>("Term")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassYearId");

                    b.HasIndex("SchoolYear", "Term", "Name", "ClassYearId")
                        .IsUnique();

                    b.ToTable("Schedule", t =>
                        {
                            t.HasCheckConstraint("CK_Term_Schedule", "\"Term\" >= 1 AND \"Term\" <= 2");
                        });
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.ScheduleDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("FinishTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("TeacherSubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DayOfWeek");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("TeacherSubjectId");

                    b.ToTable("ScheduleDetail", t =>
                        {
                            t.HasCheckConstraint("CK_Time_Detail", "\"FinishTime\" > \"StartTime\"");
                        });
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.SchoolYearInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("integer");

                    b.Property<int>("Term")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SchoolYearInfo");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Student");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.StudentClassYear", b =>
                {
                    b.Property<Guid>("StudentClassYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassYearId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("StudentClassYearId");

                    b.HasIndex("StudentId");

                    b.HasIndex("ClassYearId", "StudentId")
                        .IsUnique();

                    b.ToTable("StudentClassYear");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MaxPeriod")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectName")
                        .IsUnique();

                    b.ToTable("Subject", t =>
                        {
                            t.HasCheckConstraint("CK_MaxPeriod_Subject", "\"MaxPeriod\" > 0 AND \"MaxPeriod\" <= 5");
                        });
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<float?>("Score")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("TimeSubmit")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Submission");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.TeacherSubject", b =>
                {
                    b.Property<Guid>("TeacherSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("TeacherSubjectId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId", "SubjectId")
                        .IsUnique();

                    b.ToTable("TeacherSubject");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management.API.Models.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Assignment", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.ClassYear", "ClassYear")
                        .WithMany("Assignments")
                        .HasForeignKey("ClassYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management.API.Models.Domain.TeacherSubject", "TeacherSubject")
                        .WithMany("Assignments")
                        .HasForeignKey("TeacherSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassYear");

                    b.Navigation("TeacherSubject");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Attendance", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.StudentClassYear", "StudentClassYear")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentClassYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentClassYear");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.ClassYear", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.Teacher", "Teacher")
                        .WithMany("ClassYears")
                        .HasForeignKey("HomeRoomId");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Course", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.TeacherSubject", "TeacherSubject")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherSubject");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.CourseAssignment", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.Lesson", "Lesson")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.ExamScheduleDetail", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.ExamSchedule", "ExamSchedule")
                        .WithMany("ExamScheduleDetails")
                        .HasForeignKey("ExamScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management.API.Models.Domain.Subject", "Subject")
                        .WithMany("ExamScheduleDetails")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management.API.Models.Domain.Teacher", "Teacher")
                        .WithMany("ExamScheduleDetails")
                        .HasForeignKey("TeacherId");

                    b.Navigation("ExamSchedule");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.ExamStudentAssignment", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.ExamScheduleDetail", "ExamScheduleDetail")
                        .WithMany("ExamStudentAssignments")
                        .HasForeignKey("ExamScheduleDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management.API.Models.Domain.Student", "Student")
                        .WithMany("ExamStudentAssignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamScheduleDetail");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Fee", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.ClassYear", "ClassYear")
                        .WithMany("Fees")
                        .HasForeignKey("ClassYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassYear");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.FeeDetail", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.Fee", "Fee")
                        .WithMany("FeeDetails")
                        .HasForeignKey("FeeId");

                    b.HasOne("School_Management.API.Models.Domain.Student", "Student")
                        .WithMany("FeeDetails")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fee");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Lesson", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.LessonVideo", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.Lesson", "Lesson")
                        .WithMany("LessonVideos")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.RefreshToken", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Result", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.Student", "Student")
                        .WithMany("Results")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management.API.Models.Domain.Subject", "Subject")
                        .WithMany("Results")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Schedule", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.ClassYear", "ClassYear")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassYear");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.ScheduleDetail", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.Schedule", "Schedule")
                        .WithMany("ScheduleDetails")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management.API.Models.Domain.TeacherSubject", "TeacherSubject")
                        .WithMany("ScheduleDetails")
                        .HasForeignKey("TeacherSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("TeacherSubject");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Student", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.AppUser", "User")
                        .WithOne("Student")
                        .HasForeignKey("School_Management.API.Models.Domain.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.StudentClassYear", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.ClassYear", "ClassYear")
                        .WithMany("StudentClassYears")
                        .HasForeignKey("ClassYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management.API.Models.Domain.Student", "Student")
                        .WithMany("StudentClassYears")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassYear");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Submission", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management.API.Models.Domain.Student", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Teacher", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.AppUser", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("School_Management.API.Models.Domain.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.TeacherSubject", b =>
                {
                    b.HasOne("School_Management.API.Models.Domain.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Management.API.Models.Domain.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.ClassYear", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Fees");

                    b.Navigation("Schedules");

                    b.Navigation("StudentClassYears");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Course", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.ExamSchedule", b =>
                {
                    b.Navigation("ExamScheduleDetails");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.ExamScheduleDetail", b =>
                {
                    b.Navigation("ExamStudentAssignments");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Fee", b =>
                {
                    b.Navigation("FeeDetails");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Lesson", b =>
                {
                    b.Navigation("CourseAssignments");

                    b.Navigation("LessonVideos");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Schedule", b =>
                {
                    b.Navigation("ScheduleDetails");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Student", b =>
                {
                    b.Navigation("ExamStudentAssignments");

                    b.Navigation("FeeDetails");

                    b.Navigation("Results");

                    b.Navigation("StudentClassYears");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.StudentClassYear", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Subject", b =>
                {
                    b.Navigation("ExamScheduleDetails");

                    b.Navigation("Results");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.Teacher", b =>
                {
                    b.Navigation("ClassYears");

                    b.Navigation("ExamScheduleDetails");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("School_Management.API.Models.Domain.TeacherSubject", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Courses");

                    b.Navigation("ScheduleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
