{
 "title": "School Management API Overview",
 "tags": [
  "api",
  "dotnet"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(school_api_http_server_request_duration_seconds_count[1m])",
     "legendFormat": "Requests / sec"
    }
   ]
  },
  {
   "title": "HTTP 50xxx Custom Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(school_api_custom_error_count_total{custom_status_code=~\"50...\"}[1m])",
     "legendFormat": "Errors / sec ({{custom_status_code}})"
    }
   ]
  },
  {
   "title": "Thread Pool Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "school_api_process_runtime_dotnet_thread_pool_threads_count",
     "legendFormat": "Threads Count"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "school_api_process_runtime_dotnet_gc_heap_size_bytes",
     "legendFormat": "Working Set"
    }
   ]
  }
 ]
}